### ISSUE TITLE
使用k8s部署报错

### ISSUE THREAD

**Issue by win32fk** [sumingcheng/fastgpt-admin#1]
我是本地打的镜像

使用k8s部署一个pod失败：

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at Function.from (node:buffer:325:9)
    at authLicense (file:///app/service/auth.js:60:27)
    at file:///app/server.js:9:1
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:106:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}
Server is running on port 3001
file:///app/service/auth.js:79
    throw new Error('License 不合法');
          ^

Error: License 不合法
    at authLicense (file:///app/service/auth.js:79:11)
    at file:///app/server.js:9:1
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:106:12)

Node.js v18.19.0

**Comment by win32fk** [comment]
不小心拉到了 官方的镜像，需要认证。
自己打镜像，上传到私库，然后再用k8s拉取。
